#!/bin/bash

ufw default reject outgoing 
ufw allow out proto tcp to 147.197.236.217 port 80,443 
ufw allow in 22/tcp 
ufw allow in proto tcp to any port 80 from 147.197.236.217 
ufw enable
apachectl start
